// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf_template/internal/dao/internal"
)

// fFamliyDao is the data access object for the table f_famliy.
// You can define custom methods on it to extend its functionality as needed.
type fFamliyDao struct {
	*internal.FFamliyDao
}

var (
	// FFamliy is a globally accessible object for table f_famliy operations.
	FFamliy = fFamliyDao{internal.NewFFamliyDao()}
)

// Add your custom methods and functionality below.
