// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf_template/internal/dao/internal"
)

// famliyDao is the data access object for the table gf_famliy.
// You can define custom methods on it to extend its functionality as needed.
type famliyDao struct {
	*internal.FamliyDao
}

var (
	// Famliy is a globally accessible object for table gf_famliy operations.
	Famliy = famliyDao{internal.NewFamliyDao()}
)

// Add your custom methods and functionality below.
