// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf_template/internal/dao/internal"
)

// infoDao is the data access object for the table gf_info.
// You can define custom methods on it to extend its functionality as needed.
type infoDao struct {
	*internal.InfoDao
}

var (
	// Info is a globally accessible object for table gf_info operations.
	Info = infoDao{internal.NewInfoDao()}
)

// Add your custom methods and functionality below.
