// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf_template/internal/dao/internal"
)

// tInfoDao is the data access object for the table t_info.
// You can define custom methods on it to extend its functionality as needed.
type tInfoDao struct {
	*internal.TInfoDao
}

var (
	// TInfo is a globally accessible object for table t_info operations.
	TInfo = tInfoDao{internal.NewTInfoDao()}
)

// Add your custom methods and functionality below.
