// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf_template/internal/dao/internal"
)

// tUserDao is the data access object for the table t_user.
// You can define custom methods on it to extend its functionality as needed.
type tUserDao struct {
	*internal.TUserDao
}

var (
	// TUser is a globally accessible object for table t_user operations.
	TUser = tUserDao{internal.NewTUserDao()}
)

// Add your custom methods and functionality below.
