// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// SysCronGroup defines the fields of table "gf_sys_cron_group" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var SysCronGroup = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "bigint",
		Null:    false,
		Key:     "PRI",
		Default: nil,
		Extra:   "auto_increment",
		Comment: "任务分组ID",
	},
	"pid": {
		Index:   1,
		Name:    "pid",
		Type:    "bigint",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "父类任务分组ID",
	},
	"name": {
		Index:   2,
		Name:    "name",
		Type:    "varchar(100)",
		Null:    true,
		Key:     "",
		Default: "",
		Extra:   "",
		Comment: "分组名称",
	},
	"is_default": {
		Index:   3,
		Name:    "is_default",
		Type:    "tinyint(1)",
		Null:    true,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "是否默认",
	},
	"sort": {
		Index:   4,
		Name:    "sort",
		Type:    "int",
		Null:    true,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "排序",
	},
	"remark": {
		Index:   5,
		Name:    "remark",
		Type:    "varchar(500)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "备注",
	},
	"status": {
		Index:   6,
		Name:    "status",
		Type:    "tinyint(1)",
		Null:    true,
		Key:     "",
		Default: "1",
		Extra:   "",
		Comment: "分组状态",
	},
	"created_at": {
		Index:   7,
		Name:    "created_at",
		Type:    "datetime",
		Null:    true,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED",
		Comment: "创建时间",
	},
	"updated_at": {
		Index:   8,
		Name:    "updated_at",
		Type:    "datetime",
		Null:    true,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
		Comment: "更新时间",
	},
}

// SetSysCronGroupTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetSysCronGroupTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "gf_sys_cron_group", SysCronGroup, schema...)
}
