// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// SysCron defines the fields of table "gf_sys_cron" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var SysCron = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "bigint",
		Null:    false,
		Key:     "PRI",
		Default: nil,
		Extra:   "auto_increment",
		Comment: "任务ID",
	},
	"group_id": {
		Index:   1,
		Name:    "group_id",
		Type:    "bigint",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "分组ID",
	},
	"title": {
		Index:   2,
		Name:    "title",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "任务标题",
	},
	"name": {
		Index:   3,
		Name:    "name",
		Type:    "varchar(100)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "任务方法",
	},
	"params": {
		Index:   4,
		Name:    "params",
		Type:    "varchar(255)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "函数参数",
	},
	"pattern": {
		Index:   5,
		Name:    "pattern",
		Type:    "varchar(64)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "表达式",
	},
	"policy": {
		Index:   6,
		Name:    "policy",
		Type:    "bigint",
		Null:    false,
		Key:     "",
		Default: "1",
		Extra:   "",
		Comment: "策略",
	},
	"count": {
		Index:   7,
		Name:    "count",
		Type:    "bigint",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "执行次数",
	},
	"sort": {
		Index:   8,
		Name:    "sort",
		Type:    "int",
		Null:    true,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "排序",
	},
	"remark": {
		Index:   9,
		Name:    "remark",
		Type:    "varchar(500)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "备注",
	},
	"status": {
		Index:   10,
		Name:    "status",
		Type:    "tinyint(1)",
		Null:    true,
		Key:     "",
		Default: "1",
		Extra:   "",
		Comment: "任务状态",
	},
	"created_at": {
		Index:   11,
		Name:    "created_at",
		Type:    "datetime",
		Null:    true,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED",
		Comment: "创建时间",
	},
	"updated_at": {
		Index:   12,
		Name:    "updated_at",
		Type:    "datetime",
		Null:    true,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
		Comment: "更新时间",
	},
}

// SetSysCronTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetSysCronTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "gf_sys_cron", SysCron, schema...)
}
