// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// User defines the fields of table "gf_user" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var User = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "int",
		Null:    false,
		Key:     "PRI",
		Default: nil,
		Extra:   "auto_increment",
		Comment: "",
	},
	"name": {
		Index:   1,
		Name:    "name",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"f_id": {
		Index:   2,
		Name:    "f_id",
		Type:    "int",
		Null:    false,
		Key:     "MUL",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"delete_at": {
		Index:   3,
		Name:    "delete_at",
		Type:    "int",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"create_at": {
		Index:   4,
		Name:    "create_at",
		Type:    "datetime",
		Null:    true,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED",
		Comment: "",
	},
	"update_at": {
		Index:   5,
		Name:    "update_at",
		Type:    "datetime",
		Null:    true,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
		Comment: "",
	},
	"infoId": {
		Index:   6,
		Name:    "infoId",
		Type:    "int",
		Null:    true,
		Key:     "MUL",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
}

// SetUserTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetUserTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "gf_user", User, schema...)
}
